### ISSUE TITLE
get_nasdaq_symbols error?

### ISSUE THREAD

**Issue by raycwallace** [skillachie/finsymbols#11]
Sorry I am a novice to Python so the following may be a really green issue but...
I enter the following at python 3.5 prompt :+1:
 >>> import finsymbols
>>> xx = finsymbols.get_nasdaq_symbols()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda3\lib\site-packages\finsymbols\symbols.py", line 48, in get_nasdaq_symbols
    return _get_exchange_data("NASDAQ")
  File "C:\Anaconda3\lib\site-packages\finsymbols\symbols.py", line 61, in _get_exchange_data
    return get_symbol_list(symbol_data,exchange)
  File "C:\Anaconda3\lib\site-packages\finsymbols\symbol_helper.py", line 29, in get_symbol_list
    symbol_data_dict['company'] = row[1] 
IndexError: list index out of range

I installed using:
 pip install finsymbols

Please advise.
Best regards

**Comment by skillachie** [comment]
Just tested with Python 3. It seems to work as expected from our end. Might be something strange in your environment. Try using virtualenv

http://docs.python-guide.org/en/latest/dev/virtualenvs/

Also you need to be connected to the internet if it is the first time you are calling get_nasdaq_symbols()



```
(python3)skillachie@LoneWolf:~/Development$ pip install finsymbols
Collecting finsymbols
  Using cached finsymbols-1.0.1.tar.gz
Collecting beautifulsoup4>=4.2.1 (from finsymbols)
  Downloading beautifulsoup4-4.4.1-py3-none-any.whl (81kB)
    100% |████████████████████████████████| 81kB 2.3MB/s 
Building wheels for collected packages: finsymbols
  Running setup.py bdist_wheel for finsymbols
  Stored in directory: /home/skillachie/.cache/pip/wheels/75/91/ad/98f2a337420f25973a52c91492e4574a4c3c23fbba91ead7a2
Successfully built finsymbols
Installing collected packages: beautifulsoup4, finsymbols
Successfully installed beautifulsoup4-4.4.1 finsymbols-1.0.1
(python3)skillachie@LoneWolf:~/Development$ python
Python 3.4.3 (default, Oct 14 2015, 20:28:29) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import finsymbols
>>> xx = finsymbols.get_nasdaq_symbols()
>>> xx
[{'company': '1347 Capital Corp.', 'sector': 'Finance', 'industry': 'Business Services', 'symbol': 'TFSC'}, {'company': '1347 Capital Corp.', 'sector': 'Finance', 'industry': 'Business Services', 'symbol': 'TFSCR'}, {'company': '1347 Capital Corp.', 'sector': 'Finance', 'industry': 'Business Services', 'symbol': 'TFSCU'}, {'company': '1347 Capital Corp.', 'sector': 'Finance'
```

**Comment by raycwallace** [comment]
ok many thanks for the check.
I fear my python install was not done correctly so performing re-install.
Appreciate your quick reply.

Regards

**Comment by raycwallace** [comment]
I am using Anaconda to install python 3 and then using pip to install finsymbols.
I then use Syder as IDE.  I can get finsybols to work once from python prompt.
But from inside a script or second attempts calling at python prompt finsymbol fails as indicated before...

Any comment on Using Anaconda or Syder?

regards

**Comment by skillachie** [comment]
It is definitely with your environment .  I use VIM as my IDE so cannot help there. Another user also had some issues that he resolved himself. He also used Anaconda. Try sending him an email

https://github.com/skillachie/finsymbols/issues/7
