### ISSUE TITLE
'module' object has no attribute 'get_sp500_symbols'

### ISSUE THREAD

**Issue by Ragudude** [skillachie/finsymbols#16]
Hello, 

I have conducted a pip install of finsymbols, then attempted the following code:
`import finsymbols

sp500 = `finsymbols.get_sp500_symbols()`

pprint.pprint(sp500)`

the terminal reports an attribute error: AttributeError: 'module' object has no attribute 'get_sp500_symbols'

please advise.

Thank you.

**Comment by skillachie** [comment]
Share your script. The below works with a fresh install of finsymbols using pip

`
import finsymbols
sp500 = finsymbols.get_sp500_symbols()
`

**Comment by Ragudude** [comment]
`import finsymbols
sp500 = finsymbols.get_sp500_symbols()
print sp500`

see the attached .png for the code, the successful pip install, and the terminal indicating an attribute error.

Thank you, 
![finsymbols](https://cloud.githubusercontent.com/assets/23587679/20471616/401c21f0-af81-11e6-933c-4c327d72470b.png)

**Comment by skillachie** [comment]
I see what the problem is. Your file is also called "finsymbols.py"  As a result it is looking in that file and not the module.

Please rename your Python script to something else other than finsymbols.py

**Comment by Ragudude** [comment]
That worked! Thank you!
